version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12  # Use the appropriate Python version
    steps:
      - checkout  # Checkout the code from the repository
      
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest  # This assumes you're using pytest

workflows:
  version: 2
  test:
    jobs:
      - build